### ISSUE TITLE
毛坯房精装修

### ISSUE THREAD

**Issue by hilinxinhui** [zhouyiran-la/zhouyiran-la.github.io#1]
- 仓库主页About加上url和topics，参考https://github.com/hilinxinhui/hilinxinhui.github.io
- blog主页的title、subtitle和author等信息改成自己的名字
- 加上favicon
- 加上About页和RSS订阅功能
- 暂时关闭评论区和搜索引擎分析
- 文章加上categories和tags
- 在主页上只展示部分博客内容，开启“阅读全文”功能
- 写文章写文章写文章，可以写这些内容：
    - blog的配置流程和踩的坑
    - 学习笔记
    - 读论文的心得
    - blog形式的备忘
    - 书评
- ......

**Comment by zhouyiran-la** [comment]
感谢！
